config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: "pages#home"

  resources :donations, only: [:index, :show]
  resources :facilities, only: [:index]
  resources :donors, only: :index

  devise_scope :user do
    get 'sign_up/choose_type', to: 'registrations#choose_type', as: :choose_user_type
  end

  resources :blood_requests do
    resources :messages, only: [:create]
    collection do
      get :donor_index
      get :urgent_requests
      get :accepted_requests
    end

    member do
      patch :accept
      # patch :reject
      patch :complete
    end
  end

  resources :notifications, only: [:index, :show] do
    member do
      patch :mark_as_read
    end
  end

  resources :questions, only: [:index, :create, :show] do
    collection do
      delete :clear
    end
    member do
      get :status
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  validates :kind, presence: true

  after_create_commit :broadcast_notification

  scope :unread, -> { where(read_at: nil) }

  def unread?
    read_at.nil?
  end

  private

  def broadcast_notification
    broadcast_append_to(
      "notifications_#{user_id}",
      partial: "notifications/notification",
      locals:  { notification: self },
      target: "notifications"
    )
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def create
    @blood_request = BloodRequest.find(params[:id])
    @notification = Notification.new(notification_params)
    @notification.user = current_user
    @notification.notifiable = @blood_request

    if @notification.save
      respond_to do |format|
        format.html { redirect_to blood_request_path(@blood_request) }
        format.turbo_stream
      end
    else
      render "blood_request/show", status: :unprocessable_entity
    end
  end

  def show
    @notification = current_user.notifications.find(params[:id])
    @notification.update(read: true)

    if @notification.notifiable.is_a?(BloodRequest)
      redirect_to blood_request_path(@notification.notifiable)
    else
      redirect_to root_path
    end
  end

  def mark_as_read
    notification = current_user.notifications.find(params[:id])
    notification.update(read_at: Time.current)

    redirect_to notification.notifiable
  end

  private

  def notification_params
    params.require(:notification).permit(:kind)
  end
end

app/views/notifications/_notification.html.erb
<%= link_to mark_as_read_notification_path(notification),
            data: { turbo_method: :patch },
            class: "dropdown-item #{'fw-bold' if notification.unread?}" do %>

  <%= notification.data["message"] %><br>
  <small class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</small>

<% end %>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>

app/views/notifications/show.html.erb
<%= turbo_stream_from "notifications_#{current_user.id}" %>
<div id="notifications">
  <%= render current_user.notifications %>
</div>